# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dettrace

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  clean: true
  fetchDepth: 1
  submodules: recursive

- script: |
    nix-shell --run 'make build'
  displayName: 'Build Bazel'
