trigger:
- dettrace

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  submodules: true
  persistCredentials: true

- script: |
    lsb_release -a
    uname -a
    stat /dev/null
  displayName: 'Debugging information'

- script: |
    ( cd detTrace && make docker )
  displayName: 'Build detTrace'

- script: |
    curl https://nixos.org/nix/install | sh
    . /home/vsts/.nix-profile/etc/profile.d/nix.sh
    nix-shell --run 'make build'
  displayName: 'Build Bazel'
